# Generated by Django 4.0.4 on 2022-05-27 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCollectionApp', '0003_alter_book_username_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2500), django.core.validators.MinValueValidator(0)]),
        ),
    ]
