# Generated by Django 4.0.4 on 2022-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCollectionApp', '0004_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
