# Generated by Django 4.0.4 on 2022-05-28 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCollectionApp', '0005_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='addingDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
